"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$localip\
$kubernetes\
$directory\
$docker_context\
$package\
$c\
$cmake\
$deno\
$golang\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nodejs\
$perl\
$php\
$python\
$rlang\
$ruby\
$rust\
$scala\
$terraform\
$vagrant\
$zig\
$memory_usage\
$aws\
$azure\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$container\
$shell\
$character
"""

#$gcloud\

right_format = """
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
"""

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_metrics]
format = '\(([+$added]($added_style) )([-$deleted]($deleted_style))\) '
disabled = false

[git_status]
stashed = ''
